"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FabledLibrary.py']
DATA_FILES = ["/Users/morgan/Documents/GitHub/Fabled-Library/Source Code/icon.icns"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
